applications/induccion/urls.py
#
from django.urls import path
from . import views

app_name = "induccion_app"

urlpatterns = [ 
    path(
        'salasadmin/', 
        views.EventListView.as_view(),
        name='entry-lista',
    ),
    path(
        'create-session-token', 
        views.UpdateToken.as_view(),
        name='create-session',
    ),  
     path(
        'room-live/<int:room>/', 
        views.OpenRoom.as_view(),
        name='in-session',
    ),     
]

blog/urls.py
"""
Proyecto Curso Django
"""
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.induccion.urls')),
]

applications/induccion/models.py
from django.db import models

# Create your models here.
from model_utils.models import TimeStampedModel

from .managers import EventManager




class Attendant(TimeStampedModel):


	PUBLICO_CHOICES = (
		('1', 'Todos'),
        ('2', 'Personal Interno'),
        ('3', 'Invitado'),
     
    )


	name=models.CharField(
		'Nombre Completo',
		max_length=100,
		blank=False,
        null=False
	)


	email = models.EmailField(unique=True)


	typeCompany = models.CharField(
		'Tipo Empresa',
		choices=PUBLICO_CHOICES, 
		blank=False,       
		max_length=1,
        null=False
	)


	class Meta:
		verbose_name='Asistente'
		verbose_name_plural='Asistentes'

	def __str__(self):
		return self.name


class Expositor(TimeStampedModel):

	name=models.CharField(
		'Nombre Completo',
		max_length=100,
		blank=False,
        null=False
	)


	email = models.EmailField(unique=True)



	class Meta:
		verbose_name='Expositor'
		verbose_name_plural='Expositores'

	def __str__(self):
		return self.name



class Event(TimeStampedModel):


	ESTADO_CHOICES = (
		('1', 'Registrado'),
        ('2', 'En Curso'),
        ('3', 'Terminado'),
     
    )

	PUBLICO_CHOICES = (
		('1', 'Todos'),
        ('2', 'Personal Interno'),
        ('3', 'Invitado'),
     
    )


	title=models.CharField(
		'Tema',
		max_length=60,
		blank=False,
        null=False
	)
	description=models.CharField(
		'Descripción',
		max_length=100,
		blank=False,
        null=False
	)
	aforo=models.PositiveIntegerField(
		'Aforo',
		blank=False,
        null=False
	)
	public=models.CharField(
		'Público',
		choices=PUBLICO_CHOICES, 
		blank=False,       
		max_length=1,
        null=False
	)
	DateIni=models.DateTimeField(
        'Fecha Inicio Programada', 
        blank=False,
        null=False
    )
	dateEndProgram=models.DateTimeField(
        'Fecha Fin Programada', 
        blank=False,
        null=False
    )
	dateEndReal=models.DateTimeField(
        'Fecha fin Real', 
        blank=True,
        null=True
    )

	duration=models.CharField(
		'Duración', 
		max_length=40,
		blank=True,
        null=True
	)
	state=models.CharField(
		'Estado',
		choices=ESTADO_CHOICES,
		blank=False, 
		max_length=1
	)
	token=models.TextField(
		blank=True,
		null=True
	)

	attend=models.ManyToManyField(Attendant, through='DetailEventAttend')


	expositor=models.ForeignKey(
		Expositor,
		on_delete=models.CASCADE,
		blank=True,
		null=True
	)

	

	objects=EventManager()

	class Meta:
		verbose_name='Evento'
		verbose_name_plural='Eventos'

	def __str__(self):
		return self.title





class DetailEventAttend(TimeStampedModel):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    attendant = models.ForeignKey(Attendant, on_delete=models.CASCADE)
    dateTime_joined = models.DateTimeField(
        'Fecha  y hora de ingreso', 
        blank=True,
        null=True
    )
    dateTime_out = models.DateTimeField(
        'Fecha  y hora de salida', 
        blank=True,
        null=True


    )

applications/induccion/forms.py
from django import forms
#
from .models import Event


class EventForm(forms.ModelForm):
	
	class Meta:

		model=Event
		fields=('__all__')

					

applications/induccion/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy, reverse

from django.views.generic import (
	ListView,
	UpdateView,
	View,
	TemplateView,


)
from opentok import OpenTok
from opentok import Roles

from django.http import HttpResponseRedirect

from .forms import (
	EventForm
)

from .models import Event


global Room

class EventListView(ListView):
	template_name='induccion/list_room.html'
	context_object_name = 'eventos'
	paginate_by=3


	def get_context_data(self, **kwargs):
		context = super(EventListView,self).get_context_data(**kwargs)

		return context

	def get_queryset(self):

		# consulta de busqueda

		resultado= Event.objects.listar_eventos()

		return resultado


	def post(self,request,*args,**kwargs):

		
		room=request.POST['id']
		print(room+"eeee")


class UpdateToken(View):

	def post(self,request,*args,**kwargs):


		api_key = '47058394'
		api_secret = '6a0bd6f70f9be22bde0678e0ae81f8d608e5aea1'

		opentok = OpenTok(api_key, api_secret)
		session = opentok.create_session()
		session_id = session.session_id
		token = opentok.generate_token(session_id)

		Event.objects.create_token(request.POST['id'],session_id)

		#logout(request)
		return HttpResponseRedirect(
			reverse(
				'induccion_app:entry-lista'
			)
		)


class OpenRoom(TemplateView):

	template_name ="induccion/Conference_room.html"

	def get_context_data(self,**kwargs):

		#room = "333"
		api_key = '47058394'
		api_secret = '6a0bd6f70f9be22bde0678e0ae81f8d608e5aea1'

		#print(self.request.GET.get('room',))
		context=super(OpenRoom,self).get_context_data(**kwargs)
		

		opentok = OpenTok(api_key, api_secret)


		
		if context['room']==3:
			session_id = Event.objects.get_sala(2)
			token = opentok.generate_token(session_id[0].token,role=Roles.publisher)
		else:
			session_id = Event.objects.get_sala(context['room'])	
			token = opentok.generate_token(session_id[0].token)
		

		

		
		print (token)
		#context=super(OpenRoom,self).get_context_data(**kwargs)

		context['api_key']='47058394'
		context['session_id'] = session_id[0].token
		context['token'] = token


		return context

templates/induccion/Conference_room.html
{% extends "induccion/base_induccion.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<h2>Hello, World!</h2>

<div id="publisher"></div>
<button id="shared" class="button">Compatir pantalla </button>

<div id="subscribers"></div>


{% include "includes/footer.html" %}

{% endblock content %}

templates/induccion/base_induccion.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/myblog.css' %}">
{% endblock css %}



{% block js %}
<script src="https://static.opentok.com/v2/js/opentok.min.js"></script>
<script type="text/javascript">
        var apiKey = '{{ api_key }}';
        var sessionId = '{{ session_id }}';
        var token = '{{ token }}';
</script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="{% static 'js/opentok/testone.js' %}"></script>

{% endblock js %}

templates/induccion/detail_room.html
{% extends "induccion/base_induccion.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">


</div>

{% include "includes/footer.html" %}

{% endblock content %}

templates/induccion/list_room.html
{% extends "induccion/base_induccion.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}


<div class="grid-container">
	 <div class="grid-x grid-margin-x" style="margin-top: 1em;">
	 	<div class="cell small-12 large-8">
	 		<div class="grid-x grid-margin-x">
	            {% for evento in eventos %}

	                <div class="cell small-6 large-6">
	                    <div class="card" style="width: 100%;">
	           				
	                        <div class="card-section">
	                          <h4>{{ evento.title| truncatechars:20}}</h4>
	                          <p>{{ evento.description }}</p>
	                          <p><b>Publico</b> = 


                                    {% if evento.public == "1" %}
                                        Todos
                                    {% else %}
                                        {% if evento.public == "2" %}
                                            Personal Interno
                                        {% else %}
                                            Invitado
                                        {% endif %}
                                    {% endif %}


                            </p>
	                          <p>Aforo = {{ evento.aforo}}</p>
	                          <p>Fecha y hora = {{ evento.DateIni }}</p>
	                          <p>Duración = {{ evento.duration }}</p>
                             <p>Estado = 


                                    {% if evento.state == "1" %}
                                        Registrado
                                    {% else %}
                                        {% if evento.state == "2" %}
                                            En curso
                                        {% else %}
                                            Terminado
                                        {% endif %}
                                    {% endif %}

                             </p>

                             {% if evento.state == "1" %}
                              <form class="grid-x grid-margin-x" method="POST" action="{% url 'induccion_app:create-session' %}">{% csrf_token %}
                               <div class="input-group-button">
                               <input type="hidden" id="id" name="id" value="{{ evento.id }}">
                                <input type="submit" class="button" value="Iniciar Sala">
                               </div>
                            </form>
                                    {% else %}
                                        {% if evento.state == "2" %}
       
                               <div class="input-group-button">
                                  <a href="{% url 'induccion_app:in-session' evento.id %}" class="button warning">
                               Entrar Sala"</a>

                               
                               </div>
                                       {% else %}
                                            Evento Finalizado
                                        {% endif %}
                                    {% endif %}



                       



	                        </div>
	                    </div>
	                </div>
	            {% empty %}
	            <h3 style="color:red">No hay resultados</h3>

	            {% endfor %}
       
            </div>
	 	</div>

	 </div>

	 <!-- inicio de bloque de paginacion -->
    <div class="cell">
      {% if is_paginated %}
      <nav aria-label="Pagination">
        <ul class="pagination">
          {% if page_obj.has_previous %}
            <li class="pagination-previous">
              <a href="?page={{ page_obj.previous_page_number}}" aria-label="Page 2">Atras</a>
            </li>
          {% endif %}
          {% for pagina in paginator.page_range %}

          {% ifequal pagina page_obj.number%}
          <li class="current">
            <span class="show-for-sr">You're on page</span> {{pagina}}</li>
          {% else %}
            <li>
            <a href="?page={{pagina}}" aria-label="Page {{pagina}}">{{pagina}}</a>
            </li>
          {% endifequal %}
          {% endfor %}
          {% if page_obj.has_next %}
          <li class="pagination-next"><a href="#" aria-label="Next page">
            <a href="?page={{ page_obj.next_page_number}}" aria-label="Page 2">Siguiente</a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
      </a></li></ul></nav></div>
      
</div>

{% include "includes/footer.html" %}

{% endblock content %}